# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
# Multi-stage build for security and minimal image size

# Build stage
FROM python:3.14-alpine AS builder

# Install build dependencies
RUN apk add --no-cache \
    gcc \
    musl-dev \
    linux-headers \
    && rm -rf /var/cache/apk/*

# Set working directory
WORKDIR /build

# Copy only dependency files first for better layer caching
COPY pyproject.toml README.md LICENSE ./
COPY src/ ./src/

# Install dependencies in a virtual environment
RUN python -m venv /opt/venv && \
    . /opt/venv/bin/activate && \
    pip install --no-cache-dir --upgrade pip setuptools wheel && \
    pip install --no-cache-dir .

# Runtime stage
FROM python:3.14-alpine

# Add security labels
LABEL maintainer="Jim Scardelis <jim@jceltd.com>" \
      description="MCP Server for searching via DuckDuckGo" \
      version="0.2.1" \
      org.opencontainers.image.source="https://github.com/jimscard/duckduckgo-mcp-server"

# Install runtime dependencies only
RUN apk add --no-cache \
    libstdc++ \
    && rm -rf /var/cache/apk/*

# Create non-root user with specific UID/GID
RUN addgroup -g 1001 -S appgroup && \
    adduser -u 1001 -S appuser -G appgroup -h /home/appuser -s /bin/sh

# Set working directory
WORKDIR /app

# Copy virtual environment from builder
COPY --from=builder --chown=appuser:appgroup /opt/venv /opt/venv

# Set environment variables
ENV PATH="/opt/venv/bin:$PATH" \
    PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONFAULTHANDLER=1

# Switch to non-root user
USER appuser

# Health check (optional, can be customized based on your needs)
HEALTHCHECK --interval=30s --timeout=3s --start-period=5s --retries=3 \
    CMD python -c "import sys; sys.exit(0)"

# Run the MCP server
CMD ["python", "-m", "duckduckgo_mcp_server.server"]
